version: '2'
services:
    sentry-app:
        image: sentry
        external_links:
            - sentry-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=sentry
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sentry-mongodb:
        extends:
            file: mongodb.yml
            service: sentry-mongodb
