version: '2'
services:
    sentry-mongodb:
        container_name: sentry-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        command: mongos --configdb sentry-mongodb-config
    sentry-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    sentry-mongodb-config:
        image: mongo:3.2.10
        container_name: sentry-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
