version: '2'
services:
    sentry-mongodb:
        container_name: sentry-mongodb
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/sentry/mongodb/:/data/db/
